- name: Install and start Minikube on Production Server
  hosts: localhost
  become: yes
  tasks:
    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube with Docker driver
      command: minikube start --driver=docker
      register: minikube_output

    - name: Show Minikube startup output
      debug:
        msg: "{{ minikube_output.stdout }}"
